version: "2"
services:
  lwj-fe-service:
    build: client
    ports:
      - "80:80"
    links:
      - backend
  lwj-be-service:
    build: server
    restart: always
    ports:
      - "3333:3333"
    links:
      - mongo
  lwj-db-service:
    image: mongo:3.4
    volumes:
    - data-volume:/data/db
    ports:
      - "27017:27017"
volumes:
  data-volume:
